name: 'Docker Publish'

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'

permissions:
  packages: write

jobs:
  publish-schedule:
    name: Docker Publish Schedule

    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Prepare
        run: |
          TAG=$(grep -oP "(?<=creativeprojects/resticprofile:)([.\d]+)" Dockerfile)
          echo "TAG=${TAG}" >> $GITHUB_ENV
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: '.'
          file: './Dockerfile'
          platforms: 'linux/amd64,linux/arm64'
          push: true
          tags: |
            ttionya/resticprofile:latest
            ttionya/resticprofile:${{ env.TAG }}
            ghcr.io/ttionya/resticprofile:latest
            ghcr.io/ttionya/resticprofile:${{ env.TAG }}
      -
        name: Build and push (with docker dependency)
        uses: docker/build-push-action@v6
        with:
          context: '.'
          file: './Dockerfile'
          platforms: 'linux/amd64,linux/arm64'
          build-args: EXTRA_PACKAGES=docker
          push: true
          tags: |
            ttionya/resticprofile:latest-docker
            ttionya/resticprofile:${{ env.TAG }}-docker
            ghcr.io/ttionya/resticprofile:latest-docker
            ghcr.io/ttionya/resticprofile:${{ env.TAG }}-docker
